<?php

namespace Modules\Menu\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Modules\Menu\Entities\MenuItem;

class MenuItemsTableSeederTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        MenuItem::create([
            [
                'menu_id' => 1,
                'title' => 'Dashboard',
                'slug' => 'dashboard',
                'url' => '',
                'level' => 1,
                'order' => 1,
                'parent_id' => 1,
                //'type' => '',
                //'component_id' => '',
                'icon' => 'feather icon-home',
                //'img' => '',
                //'lft' => '',
                //'rgt' => '',
                //'parameters' => '',
            ],
            [
                'menu_id' => 1,
                'title' => 'Media Manager',
                'slug' => 'media-manager',
                'url' => '',
                'level' => 1,
                'order' => 2,
                'parent_id' => 1,
                //'type' => '',
                //'component_id' => '',
                'icon' => 'feather icon-image',
                //'img' => '',
                //'lft' => '',
                //'rgt' => '',
                //'parameters' => '',
            ],
            [
                'menu_id' => 1,
                'title' => 'Menu Manager',
                'slug' => 'menu',
                'url' => '',
                'level' => 1,
                'order' => 3,
                'parent_id' => 1,
                //'type' => '',
                //'component_id' => '',
                'icon' => 'feather icon-menu',
                //'img' => '',
                //'lft' => '',
                //'rgt' => '',
                //'parameters' => '',
            ],
            [
                'menu_id' => 1,
                'title' => 'Application Builder',
                'slug' => 'application-builder',
                'url' => '',
                'level' => 1,
                'order' => 4,
                'parent_id' => 1,
                //'type' => '',
                //'component_id' => '',
                'icon' => 'feather icon-box',
                //'img' => '',
                //'lft' => '',
                //'rgt' => '',
                //'parameters' => '',
            ],
            [
                'menu_id' => 1,
                'title' => 'Template Manager',
                'slug' => 'template-manager',
                'url' => '',
                'level' => 1,
                'order' => 5,
                'parent_id' => 1,
                //'type' => '',
                //'component_id' => '',
                'icon' => 'feather icon-sidebar',
                //'img' => '',
                //'lft' => '',
                //'rgt' => '',
                //'parameters' => '',
            ],
            [
                'menu_id' => 1,
                'title' => 'Module Manager',
                'slug' => 'module-manager',
                'url' => '',
                'level' => 1,
                'order' => 6,
                'parent_id' => 1,
                //'type' => '',
                //'component_id' => '',
                'icon' => 'feather icon-layers',
                //'img' => '',
                //'lft' => '',
                //'rgt' => '',
                //'parameters' => '',
            ],
            [
                'menu_id' => 1,
                'title' => 'User Accounts',
                'slug' => 'user',
                'url' => '',
                'level' => 1,
                'order' => 7,
                'parent_id' => 1,
                //'type' => '',
                //'component_id' => '',
                'icon' => 'feather icon-users',
                //'img' => '',
                //'lft' => '',
                //'rgt' => '',
                //'parameters' => '',
            ],
                [
                    'menu_id' => 1,
                    'title' => 'User Lists',
                    'slug' => 'user',
                    'url' => '',
                    'level' => 2,
                    'order' => 1,
                    'parent_id' => 7,
                    //'type' => '',
                    //'component_id' => '',
                    'icon' => '',
                    //'img' => '',
                    //'lft' => '',
                    //'rgt' => '',
                    //'parameters' => '',
                ],
                [
                    'menu_id' => 1,
                    'title' => 'Roles',
                    'slug' => 'role',
                    'url' => '',
                    'level' => 2,
                    'order' => 2,
                    'parent_id' => 7,
                    //'type' => '',
                    //'component_id' => '',
                    'icon' => '',
                    //'img' => '',
                    //'lft' => '',
                    //'rgt' => '',
                    //'parameters' => '',
                ],
                [
                    'menu_id' => 1,
                    'title' => 'Groups',
                    'slug' => 'groups',
                    'url' => '',
                    'level' => 2,
                    'order' => 3,
                    'parent_id' => 7,
                    //'type' => '',
                    //'component_id' => '',
                    'icon' => 'feather icon-users',
                    //'img' => '',
                    //'lft' => '',
                    //'rgt' => '',
                    //'parameters' => '',
                ],
                [
                    'menu_id' => 1,
                    'title' => 'Permissions',
                    'slug' => 'permissions',
                    'url' => '',
                    'level' => 2,
                    'order' => 4,
                    'parent_id' => 7,
                    //'type' => '',
                    //'component_id' => '',
                    'icon' => '',
                    //'img' => '',
                    //'lft' => '',
                    //'rgt' => '',
                    //'parameters' => '',
                ],
            [
                'menu_id' => 1,
                'title' => 'Plugins',
                'slug' => 'plugins',
                'url' => '',
                'level' => 1,
                'order' => 8,
                'parent_id' => 1,
                //'type' => '',
                //'component_id' => '',
                'icon' => 'feather icon-paperclip',
                //'img' => '',
                //'lft' => '',
                //'rgt' => '',
                //'parameters' => '',
            ],
            [
                'menu_id' => 1,
                'title' => 'Settings',
                'slug' => 'settings',
                'url' => '',
                'level' => 1,
                'order' => 9,
                'parent_id' => 1,
                //'type' => '',
                //'component_id' => '',
                'icon' => 'feather icon-settings',
                //'img' => '',
                //'lft' => '',
                //'rgt' => '',
                //'parameters' => '',
            ]
        ]);
    }
}
